# Generated by Django 4.0.4 on 2022-04-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Игра',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('telegram_id', models.PositiveIntegerField(verbose_name='Телеграм ID пользователя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('steam', models.CharField(max_length=150, verbose_name='Имя пользователя в Steam')),
                ('about', models.TextField(verbose_name='О себе')),
                ('register_date', models.DateField(verbose_name='Дата регистрации')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.game', verbose_name='Основная игра')),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
