# Generated by Django 4.0.4 on 2022-04-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_game_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
