# Generated by Django 4.0.4 on 2022-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_profile_flag_profile_is_register_alter_profile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=250, null=True, verbose_name='Телеграм username'),
        ),
    ]
