# Generated by Django 4.0.4 on 2022-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vision',
            field=models.BooleanField(default=False, verbose_name='Видимость профиля'),
        ),
    ]
